# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c84f2895ccfeefd42a7b543a8efbf86138ce98627fe4528e6eb4e050db1bbff5df31dcb9de5c75a3d12e2a7304db25573ce2798abd1ba3379632c71aed5020d

test:
  secret_key_base: 6e5633e8ea6460bff2732945cc2ec6996241cb25a7e4b3be4691bf8b553b957dafc10384e76647f5528303eda2d5f7d0c9644a3faf01647e1aa7a255c10b9db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
