# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1da133aec126af5acc2a8b615c58f3f42946fb84751706b11f4c2c30c6369dab55ca416184f035be05bfefd650311f08c8a4e49d01fad7d3a85294907e7dfc45

test:
  secret_key_base: db380b5f0e4441c3f87b6ec3c7283892f79b83925b6fddb83759a8097384528e9cffd71e01960b796f1caa9c7f3c3f3357e8746f89ce0f5c5f350c07dfb6e909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
