# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b441b92b00345f50afa5d684fcda5c6577c25ccbfbbea80350bfc0ca6118b227e97500aa1ac408d0d4b6b7660f708633a686494f0c610920f51dff5e72c79084

test:
  secret_key_base: cb9eb0874d15bc671e4a8e40073f490d8530cc9dce23af0a84133836240d9e5f92104338a2fa62361d1775835ea9416a865059bb03252b697860199a114d381c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
