# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d48aa9c90745d79fd3f4be99e829060bf98f55f58def41d5215853ab81f2335992404b510c0e1cf58298b123d405c7b03e5a7ae152b8224957d18c7b5695a996

test:
  secret_key_base: 02c1bb414cc28c46069f1efe42916b749b51a1fee5871307a579dabc6731458bb96671f099beb2e1f28e9b910b9e4ac898bf32340419c26cde69a865af61616f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
