# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e0aa4754204724430ffbfacfc3c9df7b72c1c46f582492c24f80da315a070e0bb16fdd1c55053316633fbb1d891977e6f0f4cae8376a40413479d2e59dcd87b

test:
  secret_key_base: 43e8363a0f4e2c525349e70e1eb67120b6476771987dac9045e604350ae05f9e5ab34cc4ef562fc7469421313a837009c2972d1906fefd525dc7e700ea7bbe8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
