# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792b6c4f8ca679b7b553f8cf91f93b3ccb7376d69552a2033d15a08b10ae545ba30d15c82b8e7912c96b97335b21396ce82e924165ee6c97a6cc7d38cca4265b

test:
  secret_key_base: b46fe7153d3e26cb4fad4452c69516a6832502582129a30d7fc3c293d52f83c2170a41940dd312858af5204e2be3032099b470dc8623499bd1b11e343369e0ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
